import {
  FETCH_COURSE_QUERY,
  FETCH_PARTICIPANTS_QUERY,
  FETCH_COURSES_COUNT_QUERY,
  FETCH_COURSES_QUERY,
} from "./course/courseQuery";

import {
  FETCH_FACE_PHOTOS_COUNT_QUERY,
  FETCH_FACE_PHOTOS_QUERY,
  FETCH_FACE_MATCHER_IN_COURSE_QUERY,
} from "./facePhoto/facePhotosQuery";

import {
  FETCH_NOTIFICATIONS_QUERY,
  FETCH_UNCHECKED_NOTIFICATIONS_QUERY,
} from "./notification/notificationsQuery";
import { GET_WARNING_COUNT_QUERY } from "./warning/getWarningCountQuery";

import {
  FETCH_ATTENDANCE_LIST_COUNT_IN_COURSE_QUERY,
  FETCH_ATTENDANCE_QUERY,
  FETCH_ATTENDANCE_LIST_IN_COURSE_QUERY,
} from "./attendance/attendanceQuery";

import { FETCH_TRX_LIST_IN_ATTENDANCE } from "./trx/trxListInAttendanceQuery";

export { FETCH_COURSE_QUERY, FETCH_PARTICIPANTS_QUERY };
export { FETCH_COURSES_COUNT_QUERY, FETCH_COURSES_QUERY };
export { FETCH_UNCHECKED_NOTIFICATIONS_QUERY, FETCH_NOTIFICATIONS_QUERY };
export { GET_WARNING_COUNT_QUERY };
export {
  FETCH_FACE_PHOTOS_QUERY,
  FETCH_FACE_PHOTOS_COUNT_QUERY,
  FETCH_FACE_MATCHER_IN_COURSE_QUERY,
};
export {
  FETCH_ATTENDANCE_LIST_COUNT_IN_COURSE_QUERY,
  FETCH_ATTENDANCE_QUERY,
  FETCH_ATTENDANCE_LIST_IN_COURSE_QUERY,
};

export { FETCH_TRX_LIST_IN_ATTENDANCE };
