apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: attendlytical
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/standard/default/mongo-data-pv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  claimRef:
    namespace: attendlytical # Bound to specified PVC
    name: mongo-data-pvc