export const actionTypes = {
    LOGIN_ACTION: "LOGIN",
    EDIT_PROFILE_ACTION: "EDIT_PROFILE",
    LOGOUT_ACTION: "LOGOUT",
  
    SET_IS_INITIAL_ACCESS_ACTION: "INITIAL_ACCESS",
  
    FETCH_COURSES_DONE_ACTION: "FETCH_COURSES_DONE",
    LOAD_COURSES_ACTION: "LOAD_COURSES",
    ADD_COURSE_ACTION: "ADD_COURSE",
    DELETE_COURSE_ACTION: "DELETE_COURSE",
    ENROL_COURSE_ACTION: "ENROL_COURSE",
    WITHDRAW_COURSE_ACTION: "WITHDRAW_COURSE",
  
    FETCH_NOTIFICATIONS_DONE_ACTION: "FETCH_NOTIFICATIONS_DONE",
    PRESSED_NOTIFICATION_ACTION: "PRESSED_NOTIFICATION",
    LOAD_NOTIFICATIONS_ACTION: "LOAD_NOTIFICATIONS",
    SET_UNCHECKED_NOTIFICATION_COUNT_ACTION: "SET_UNCHECKED_NOTIFICATION_COUNT",
  
    SET_INITIALCOUNTDONE_ACTION: "SET_INITIALCOUNTDONE",
    GET_ENROLCOUNT_ACTION: "FETCH_ENROLCOUNT",
    FETCH_ENROLMENTS_DONE_ACTION: "FETCH_ENROLMENTS_DONE",
    LOAD_ENROLMENTS_ACTION: "LOAD_ENROLMENTS",
    ACCEPT_ENROLMENT_ACTION: "ACCEPT_ENROLMENT",
    REJECT_ENROLMENT_ACTION: "REJECT_ENROLMENT",
  };